# Site settings
title: D. Stoppacher's research blog on computational astrophysics
email: dstoppacher@ucsc.edu
url: "https://dstoppacher.github.io/" # the base hostname & protocol for your site
github_username:  dstoppacher
permalink:   /:title/

markdown: kramdown
theme: jekyll-theme-dinky

# Build settings
mathjax: true
defaults:
    -
        scope:
            path: "" # empty string for all files
            type: "pages"
        values:
            layout: "default"
    -
        scope:
            path: "" # empty string for all files
            type: "posts"
        values:
            layout: "post"
    -
        scope:
            path: ""
            type: "draft"
        values:
            layout: "post"
    -
        scope:
            path: ""
            type: category
        values:
            layout: "default"
